{{- if .Values.database.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-global
  labels:
    app: db-global
spec:
  serviceName: db-global
  replicas: 1
  selector:
    matchLabels:
      app: db-global
  template:
    metadata:
      labels:
        app: db-global
    spec:
      {{- if $.Values.global.image.registry }}
      imagePullSecrets:
        - name: ghcr-secret
      {{- end }}
      
      {{- with .Values.database.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
      - name: postgres
        {{- if $.Values.global.image.registry }}
        image: "{{ $.Values.global.image.registry }}/db-postgres:{{ $.Values.global.image.tag }}"
        imagePullPolicy: {{ $.Values.global.image.pullPolicy }}
        {{- else }}
        image: "db-postgres:local"
        imagePullPolicy: IfNotPresent
        {{- end }}
        ports:
        - containerPort: 5432
          name: dbport
        env:
        - name: POSTGRES_USER
          value: {{ .Values.database.user | quote }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.database.password | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.database.dbName | quote }}
        # Reducimos cuotas para asegurar que quepa sin OOMKilled en t3.medium
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data

  volumeClaimTemplates:
  - metadata:
      name: pgdata
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.database.storageSize }}
      {{- if .Values.database.storageClassName }}
      storageClassName: {{ .Values.database.storageClassName | quote }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: db-global
  labels:
    app: db-global
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: db-global
{{- end }}