apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    {{- if eq .Values.global.environment "aws" }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      # ============================================================
      # 1. ENRUTAMIENTO DE BACKENDS (Microservicios API dinámicos)
      # ============================================================
      {{- range $name, $config := .Values.backends }}
      
      {{- if $config.apiPaths }}
      # Si el backend maneja múltiples rutas explícitas (Ej: ms-mantencion)
      {{- range $apiPath := $config.apiPaths }}
      - path: {{ $apiPath }}
        pathType: Prefix
        backend:
          service:
            name: {{ $name }}
            port:
              number: {{ $config.port }}
      {{- end }}
      
      {{- else }}
      # Ruta estándar automática para los demás microservicios (/api/v1/nombre)
      - path: {{ printf "/api/v1/%s" (trimPrefix "ms-" $name) }}
        pathType: Prefix
        backend:
          service:
            name: {{ $name }}
            port:
              number: {{ $config.port }}
      {{- end }}
      
      {{- end }}

      # ============================================================
      # 2. ENRUTAMIENTO DE FRONTENDS (Archivos estáticos HTML/JS)
      # ============================================================
      {{- range $name, $config := .Values.frontends }}
      {{- if not (eq $name "front-administracion") }}
      - path: {{ $config.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ $name }}
            port:
              number: 80
      {{- end }}
      {{- end }}
      
      # Ruta Raíz (/) -> front-administracion (Panel global)
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front-administracion
            port:
              number: 80